kind: ENC[AES256_GCM,data:l60m5yBW,iv:FZFCCaVdz2y1E2C855hAfE6rt8UGrmiLCcGleeK2Y8o=,tag:2Lkyo5V5+OSsSwks7UONpQ==,type:str]
ansible_user: ENC[AES256_GCM,data:fF7pLklM3zrCcPk=,iv:9mJ9kGVVTmMPDpF3pN3URKOPwR0gdPB4am0ee7ex6JI=,tag:og0VHTgZ3tHkeNzk+fhpTQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:skEg+MUJB8rxvxyeEAGfww==,iv:rJH8JVm5/s5fCiLYCKawiwIDewPEHMyeTV/G+XKoYWE=,tag:vLyJW5dmdy9n92BDjFXsKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd1JybTRMaGwrQUdsak1M
            cFdRUHVvcVJhdHE0cGMyZndDV0NmRmFUWFQ0ClVGdms3QWl1Zzd5aWVCRXBRME8z
            dW8xUkNLWnpVZ25sNGZlbThHWVFDRjAKLS0tIG81TlUvOHQyUzFEOU54NG9nMHpM
            KzViLzhXSjZJdmdNZGxWZVdhd0luWUkKEEr0wiBrZl29tQF7u4pJKfLgQn6lFh0d
            9r8qX7RVckEb6mfTv3yGyUayzjwSp2lOuOVWES9EO8EtGJNsYB3Fsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T17:53:37Z"
    mac: ENC[AES256_GCM,data:rzs73ZqhkmfTAdvs30Qik5MiJsH0YuRotOS2fDCOO+p52YIA/5UKOvpYhFL2Jgd6bt3cugI8xLEudEOknIDGjlKz1ZcP8RQV8AIgS7GPJwRITTmTIIXEsg9VaUf1oU7j9uGRlVI8zuuFFNUMBFze6Yw/mrOs8iTsJZDUKwZy6h4=,iv:7wuSyzQaC03bcTYxFL6GRNUHHpNesDITjIb1msw+EV8=,tag:VMPIizRBog36Pi2GE83ehQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
