---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-prometheus
  namespace: flux-system
spec:
  path: ./kubernetes/apps/network-monitoring/prometheus/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  # dependsOn:
  #   - name: security-onepassword-connect
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: prometheus
      namespace: network-monitoring
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 1m
