---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - grafana-secrets.yaml
  - helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana
