apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:sXRf1GrgPWc+/erRhIvaVgZkP78nv44ao5Vu3/dCuJ74ghGkmhd6Eg==,iv:RcYIxqqEAjajPKaUb7yIVnVfv8WDBMGYVJY8dULrJX8=,tag:6L74QUi4PGSyF4Q2pNR4Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cVBZOWZHRVl2TnJ0TW9X
            dUZ0MkkrTEFOcXZDOGRLTkUrdlpjRkN2ZFhvCjNXUmJJbTMvRkZsRWpZZXFGM2l6
            ejh6TlFwYldNTHgxNXM4KzUrdkx6WkkKLS0tIENXWVJOdTJyMzhhWjE4MjlCQ3Q1
            WWQ3UWNUQmFMcTByT1BnQjBqanR3ZUkKyqf+QRgOXTVcbE0MJZGJKPYDlxs5E3On
            A8cEv56yLpsaKTwl5GoOZtnsMMUkKIC3KaXYcDwrMcb7rvmcsuU4YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-12T18:50:57Z"
    mac: ENC[AES256_GCM,data:YsvdPv6Yj+NkAygG+7O11NfyfDbtR+cgBWdUila7TCFbun5BWm+L13eWs9sfsgnatjsk+Q3VQJdIBTOfhKQo+1uct3vX2LRteCbIXoQ/9IYx218aPld7COXQLU/BlaIZX8PgC2yqKmRgWK7oxOWJ2ZV/DLLVAdGr86m9q22sd/A=,iv:S6JVZ6IRpxcgB0hkwMu4Tw2qgZ2sU8NjcSWjpuG+ehg=,tag:JipjUBhQTqmoATmjo4zGxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
