apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:x5a3N1gMLr0lz5cXh9qw8alpoNNBuDt1bEWrlDP2Bnth/LlrruDaZw==,iv:NlFceVDewG7uswh0UicjbugTbR7Digu+4Ic6VCm5P90=,tag:J7dKXslQjmdMO6lT1muMGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRHVMTjR2b205MmFxMUN0
            aXVZNlBWZVR0NUZKVXNhZW5SUEZsZjBNSUVNCk4vRmlMQWFQUHE4U3pOdTlOMDZZ
            aDhnZzg1MFpvVHU4dVE3ckRMWHhEMDQKLS0tIHJLUFN1RHJ0SVY5Q3gvZUc1R0RB
            RXFzVDJvVDJYS3ByU3pLVVhGYUIvSE0K/zO8+/j3RltvWx/rUiSqzD/vVIu/Bf5A
            aJlgS7BuEW66ajRjDf+85AR3Y0NdDrwhwWxoC3Wks0IVc33FS79c9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T16:39:08Z"
    mac: ENC[AES256_GCM,data:hK9jRCMNOrpLyvOZlPc9Alg81dB2grAAfTNE7RdgS5+vOaDZIZBvfxg+OtnW7mYC6sXX83v1wHXhASBuzHKuD4xEyWk2LZVQf9VLs0HdsQFKCGNqYK2Qi+IO76qKbiRvEy6GDfMpAhp4DuyKaF8ShaQ0uc9S29qNHy0tVOi3x7A=,iv:YtGWDPztjakdauaMLKWbZpCUt2b+Ucc+gJiEMReXPwI=,tag:QBs59UJEGY5kOinsLGcfxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
