apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:tYQsEApmd5O6tkgTy8A1nFJ2TwYg/piRbdr3RB6zXbabJvO/Ww==,iv:YdeoESp8P7cB4+52f5JmqgzrnYaD9fgG+auri1NRzvc=,tag:AXRemXAM5/h7Ds9gCLKbhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldGtVL1M5V1QzR1RzK3li
            WEk0d0V0STg3QUJRY2dON1VSSUlhbEFvYVIwCk9MMVFtejZqME5sUjR0eUUxZEJm
            WERBa1g3Wm1LSUtzdiszdnpnWmM0K2sKLS0tIFFVZVBSUmNQM2kzUGxIRGxBMlY0
            Um9lbjhFclMzSUZxdjQzajBlZjhDSU0KV7qpNEzbGEzQO1AeuleNfR5TzwlqskWx
            XSPRlLVGuPCkP6WcQH3605Gui2GPAJLfrokpO5RiALpmMFXVDphTFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T17:53:37Z"
    mac: ENC[AES256_GCM,data:h3VAccl+VE7cLARphyVXrSTZJpru1/6FBu93MDG6PXnswUhzO4suAfauL9KHpt1M+P9rZ962Ex7OOa2kYYS0H1noWL5c75RNV0WscXMCkkH+o+yLE9JoyI1eBJnHuk1g/SBf/lbjpkUG9/cPyBQuPGx4wAfLJNwxO5SOU91U+mo=,iv:2zsC9RrUhAXNOVsEPQ6VECv6pJHttSYMVHWdV8S7ShM=,tag:apPsA7FvGw4Yyr+AWOGPKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
