apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:HQJJizIGcSEEtgg4znRLZGJi7uVv,iv:Y203EAIr580a6hwAGRDA19nFqFbwM1G6uTTbRs86Uds=,tag:511Y49SXwF5dGSa7jyv9fA==,type:str]
    api-key: ENC[AES256_GCM,data:kSF9Km+DbRDRtsdlkIO7ahd+7ixqE7GGA2oGTCWCAnFd3/Ja6Q==,iv:RU/dq48Byx/u9ylEjulXqrPN6wkbzVqPgLngw7L9q/o=,tag:H+woLNdA9TsexknWpZkSDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncVY3Yjk5VmR5ZG1lM2l5
            TUc4em5jMjVtYnpQanZRdWRrUGVJZnE1YTFFCnVMWVlDUncveHpKMGlqYzNocTRr
            TVhEMi83NnhLdC9HaXdoWW8vdVZiTGMKLS0tIEhQcG5sUW8vakVtVGpreE5qL1VV
            UUtkRjRFWTIzcFZjWkZyWGNwcFU4aU0KNNGxoYmdfSFlbH005rsu53yP44Ze2tgW
            vwhJUazNtCG7H+2WgZe/l7WnJLSAX4gWZaRC7w5eT9wJL4kt+D3e2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T17:53:37Z"
    mac: ENC[AES256_GCM,data:UVMs3VNdXNYqsnRhDO2AAGGw21HgMymV0ODKTDqnh9RpBmaL8YCskY2MdoDLKw/Lyx4LWWsqJH5k71WV2pn1Vs2dnc3Oqt/0xlpkKDOVda9B0GF3SSOT/iiX0SNxqaaLeQlQxnIN0CK8RjQbv3jzBMGoAPVtvnLcvh5IkEhgCyM=,iv:pfvShz3320tfNYl4K62UMG0pFGYyRqPuk2B9OhIOaj8=,tag:f0D4hDT+Uva6HmW6J3m5VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
