apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:VPVqMMhoNOoocnLEt0MaC2wOTD29ukeAoZaAk2FEYDxocWmbQa98IHCE87EEJmXR4owVnC0kAiXuNbsh,iv:uG3Z60RagDKPgJ4xQ0kLGSD3qmk/PSG12hYZwHPa1ho=,tag:j8ME38NvpOx/DpsPeLJ46A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K2hic3VCbkZURUpnYWMw
            NXF2dE9qOEVUZWtlSFE0VGdveDVxWER2aldVClM5SmJiQ2hNU3daczhBdkJWbVFX
            aHZnemFEV0I3MndydFkvOGZIQjg0R00KLS0tIHBHN1dHTlpJbkFUaDVXZlBFMVNL
            cHB3TzhaSE8zSGhKYmV2b01vRkFyRkEKHZjGvd7L5qHhUoBBgik1ZWXbFkG4fvZV
            pT729hq9BGKJOGrzf1S6I1DFqJ65Krj69/txohYF/BAnrQTtAf+nrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T16:39:10Z"
    mac: ENC[AES256_GCM,data:k58jFMq2TlK+VYKojTNe5Iq1Z9Pry4ytUYQ2yQ0pGn1Zv/AFXCN+XjipTL4g7lD4gl5sl/OpgRlxNM7eLk17EYfUz63N07u/7AgIVVwygnS6awo5Obmf6Dd+HUxDivDE82fLs0nOQpQitX4xzzJ0GOv7QtN+Kw9RSm8zPtx9VdI=,iv:jY8IP9p6YEM38j40nlCkmaz8LSHbNfNjzIlEVJH1fus=,tag:vAA+8duWUXXaNp2g13G6Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
