---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.74.8"
  METALLB_LB_RANGE: "192.168.74.240-192.168.74.250"
  METALLB_K8S_GATEWAY_ADDR: "192.168.74.240"
  METALLB_INGRESS_ADDR: "192.168.74.241"
