apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4zrzLX78Tfw=,iv:04IblP1mEFzzqdO3E9X/t7cxbOcryHLm2Y8WpCjy2Ck=,tag:/kFdDdCabxAgIZjOcf+FzA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vZbqah7wkbRoIFeNEjZMyFAncV9l,iv:3L2yt7fC7FPD2QQQ+pQX/oB6IsZJZ7H38SHOKO3ddtI=,tag:Q2gx+LekN969KFSVOpzXQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age199phw7jrz5jaey3keqxl3hkygq4q5m2w0h5wn6d0dgn68zjvj3ysyqjfnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y1J4Nk5qSEpWMWJTMWd5
            TzVHVHJhTTVrUWFHK2ROVFBzVG93SGxhQVhFClliWVpMazJLMTZkN0RlZXJ5cWgv
            Q1hta2I5QmsrTlN2R2Y1Szh6a2taNHcKLS0tIGtMdzhaRUNaSDJLQ3c5QTRmYWI0
            RHJnbTc3aG0rdTZFUE1SeUMwc25KN3cKOH2rOsBULOb1N85skPXlcd5kI+H0vU0x
            GOGhD+98Vmef1kSxNZDjjUaBRDlLbgrAFkIhDzS0x+xkOvjivkQ0Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T16:39:07Z"
    mac: ENC[AES256_GCM,data:sZb6IjwgJfVNvrZfuow8h7LmR37LRpe3CaOWqIH/ZD4vxW5b5bvQDDCR3M7phRWEEkiHNVE+v8xJ1h+fOy2CXP1dA3v0MfPHDAJNqFo/lelydKuR0Ix5vzV5h4XV5ZMhX8zvDuw0EugaVpH/G+L7L92yiKedcncerPLjIgeZIrA=,iv:cenG5B56f+sbUm0Zyy9ioTRUczRGWzT13+7/RhIEiIs=,tag:dH2tbzRegCXb3SisbY+DOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
